# Target database settings
db_settings:
  # Connection credentials
  credentials:
    host:
    database:
    user:
    password:
  # Schema
  schema: dof
# Countries input data file settings
countries:
  # Column name to use for mapping countries names/codes to oas_code in the target database
  src_column: iso3
  # Columns map:
  # key: country name/code in the source file
  # value: country oas_code in the target database
  columns_map:
    CAN: CA
    MEX: MX
    PRI: PR
    BHS: BS
    ATG: AG
    AIA: AI
    ABW: AW
    CUB: CU
    DMA: DM
    DOM: DO
    HND: HN
    HTI: HT
    JAM: JM
    CYM: KY
    LCA: LC
    MSR: MS
    TCA: TC
    VGB: VG
    VIR: VI
    ASM: AS
    FSM: FM
    GUM: GU
    KIR: KI
    MHL: MH
    MNP: MP
    PLW: PW
    RUS: RU
    WSM: WS
    USA: US
# USA states input data file settings
us_states:
  # Column name to use for mapping USA states names/codes to oas_code in the target database
  src_column: "state_code"
  # Columns map:
  # key: USA state name/code in the source file
  # value: USA state oas_code in the target database
  columns_map:
    AL: "01"
    AK: "02"
    AZ: "04"
    AR: "05"
    CA: "06"
    CO: "08"
    CT: "09"
    DE: "10"
    DC: "11"
    FL: "12"
    GA: "13"
    HI: "15"
    ID: "16"
    IL: "17"
    IN: "18"
    IA: "19"
    KS: "20"
    KY: "21"
    LA: "22"
    ME: "23"
    MD: "24"
    MA: "25"
    MI: "26"
    MN: "27"
    MS: "28"
    MO: "29"
    MT: "30"
    NE: "31"
    NV: "32"
    NH: "33"
    NJ: "34"
    NM: "35"
    NY: "36"
    NC: "37"
    ND: "38"
    OH: "39"
    OK: "40"
    OR: "41"
    PA: "42"
    RI: "44"
    SC: "45"
    SD: "46"
    TN: "47"
    TX: "48"
    UT: "49"
    VT: "50"
    VA: "51"
    WA: "53"
    WV: "54"
    WI: "55"
    WY: "56"